name: pywk99
channels:
  - conda-forge
dependencies:
  - cartopy
  - cmocean
  - dask
  - healpy
  - ipykernel
  - ipython
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pytest
  - python>=3.9
  - shapely
  - xarray
  - pip:
      - -e .