name: pywk99
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pytest
  - numpy
  - pandas
  - xarray
  - netcdf4
  - shapely
  - matplotlib
  - cartopy
  - cmocean
  - ipython
  - ipykernel
  - pip
  - dask
  - pip:
    - -e .

